spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adminmodule
    username: root
    password: Venkat_147
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


  mail:
    host: smtp.gmail.com
    port: 587
    username: naniii.k99@gmail.com
    password: sczthxhhfynjbjmi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true  
  
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
 
               