spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adminmodule
    username: root
    password: Venkat_147
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
